name: hlayiso
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # BASE
  nb_utils: ^5.0.8
  google_fonts: ^5.0.0

  # UI
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.1.0
  package_info_plus: ^4.0.2
  flutter_speed_dial: ^7.0.0

  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.0.6+5

  # STORAGE & PERMISSION
  permission_handler: ^12.1.0+2
  path_provider: ^2.0.11
  provider: ^6.0.5

  # CONNECTIVITY
  http: ^1.0.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.8
  store_redirect: ^2.0.1

  # Firebase
  firebase_in_app_messaging: ^0.7.3+2
  firebase_messaging: ^14.6.2
  firebase_core: ^2.8.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^3.5.0

  # ADS
  google_mobile_ads: ^3.0.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^5.7.2+3

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter
  flutter_downloader: ^1.10.4
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.4
  mobx_codegen: ^2.1.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
